package com.bankflow.api.domain;

public enum AuditAction {
    USER_REGISTERED,
    LOGIN_SUCCESS,
    REFRESH_TOKEN_ROTATED,
    LOGOUT,
    LOGOUT_ALL,
    ACCOUNT_CREATED,
    DEPOSIT_COMPLETED,
    WITHDRAWAL_COMPLETED,
    TRANSFER_COMPLETED,
    TRANSFER_REVIEWED,
    ACCOUNT_STATUS_CHANGED,
    IDEMPOTENT_REPLAY
}
